language: generic
services:
    - docker

before_install:
  - docker build -t awiegers/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true awiegers/react-test npm test

after_success:
  - docker build -t awiegers/multi-client ./client
  - docker build -t awiegers/multi-nginx ./nginx
  - docker build -t awiegers/multi-server ./server
  - docker build -t awiegers/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push awiegers/multi-client
  - docker push awiegers/multi-nginx
  - docker push awiegers/multi-server
  - docker push awiegers/multi-worker
